### ISSUE TITLE
Licence clarification

### ISSUE THREAD

**Issue by JoesCat** [nanjizal/hxSpiro#2]
Hi @nanjizal,
Please check Raph Levien's original spiro code, and please note that in addition to the GPL, there is also a patent grant that goes with the code (process). Please include the additional README file, https://github.com/fontforge/libspiro/blob/master/README-RaphLevien or something similar.

**Comment by nanjizal** [comment]
JoesCat

I have added a specific readme in regard to the US patent, but software patents are not widely accepted in UK or Europe and I am based in the UK, and I do not want to encourage wide acceptance, so I am happy to reference it but not happy to imply that it's a requirement since that is not totally clear that this is the case outside the US, I hope that this document is acceptable given the grey aspect of software patents in UK.

https://github.com/nanjizal/hxSpiro/blob/master/US_Patent.md

I was unsure reading the Patent if there was any problem with me releasing GNU 3 examples of Spiro code that users can modify to create shapes and export to Bezier curves, perhaps you can clarify?  I don't want to upset Raph so any advise welcome I am just keen for users to explore Sprio concepts.  I am a bit sad that I can't release the code under MIT so that more users can create, I normally always share my work under MIT, but having asked Raph I have kept it GNU 3 as per the two repositories that the work was based on.

I am a big fan of projects like inscape, blender and gimp etc...  but feel that code that is MIT will be more widely used by both open and closed source projects perhaps as opinions on licenses evolve his views may change.  Haxe foundation is based in France so unlikely that Haxelib would uphold software patents either.

But not wanting to cause problems, just not keen to embrace the patent culture of America which I think even often has patent on genes and chemicals found in nature, and is far too corporate biased, I hope you understand my concern with applying something that is not actually law in the UK.  I am unsure on github status in this regard but feel that since I have highlighted the patent as per your request it is up to the user how they interpret it's applicability.

Was actually hoping you might try the code out and give feedback on improvements the demo needs some work for sure.

Best Regards

Nanjizal

P.S. - I noticed when Facebook release code under BSD-3 they expect any contributors to sign up to additional conditions and patents etc.., I think opensource community should move towards MIT/BSD without additional claims, as I feel software developers need to sell software solutions to live but also need to share generic software to improve the quality and knowledge.  Maybe I am part of the next generation of opensource developers, that have to work to live but want to share at the same time.

**Comment by JoesCat** [comment]
Understood (about Europe's stand on patent issue),
however, this is more a case of details, like crossing the 'T' and dotting the 'i', and doing due-diligence on your part. Even though Haxelib is hosted in France, it is expected that it's going to be shared across the planet, and if people are expected to respect it's license, Haxelib too, should follow suite with other licenses too regardless of which country it came from.

Thanks - and hope you have a Happy New Year,
Joe
